spring:
  datasource:
    url: jdbc:h2:mem:ims;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
